window.questions = ["What is your greatest weakness?",
"What is your greatest strength?",
"How will your greatest strength help you perform?",
"Are you lucky?",
"Are you nice?",
"How would you describe yourself?",
"Describe a typical work week.",
"Describe your work style.",
"Do you consider yourself successful? Why?",
"Do you work well with other people?",
"Do you take work home with you?",
"How are you different from the competition?",
"How do you view yourself? Who do you compare yourself to?",
"How many hours do you normally work?",
"How would you adjust to working for a new company?",
"How would you describe the pace at which you work?",
"How do you handle stress and pressure?",
"What motivates you?",
"Are you a self motivator?",
"What do you find are the most difficult decisions to make?",
"Tell me about yourself.",
"What has been the greatest disappointment in your life?",
"What are you passionate about?",
"What are your hobbies?",
"What are your pet peeves?",
"What do people most often criticize about you?",
"What is the biggest criticism you received from your boss?",
"What is the worst thing that you have ever gotten away with?",
"What is your dream job?",
"What is your professional development plan?",
"What makes you angry?",
"When was the last time you were angry? What happened?",
"Why did you choose your major?",
"Why did you go back to school?",
"Why should I take a risk on you?",
"If you could relive the last 10 years of your life, what would you do differently?",
"If the people who know you were asked why you should be hired, what would they say?",
"Do you prefer to work independently or on a team?",
"Give some examples of teamwork.",
"More teamwork interview questions.",
"What type of work environment do you prefer?",
"How do you evaluate success?",
"If you know your boss is 100% wrong about something how would you handle it?",
"Describe a difficult work situation / project and how you overcame it.",
"Describe a time when your workload was heavy and how you handled it.",
"Questions which don't have a right answer.",
"More job interview questions about you.",
"Are you overqualified for this job?",
"Describe how you managed a problem employee.",
"How did you impact the bottom line?",
"What applicable attributes / experience do you have?",
"What part of the job will be the least challenging for you?",
"Which parts of this job are the most challenging for you?",
"What philosophy guides your work?",
"What strength will help you the most to succeed?",
"Why are you interested in taking a lower level job?",
"Why are you interested in a non-management job?",
"Name of company, position title and description, dates of employment.",
"Questions about your resume.",
"What were your expectations for the job and to what extent were they met?",
"What were your responsibilities?",
"What major challenges and problems did you face? How did you handle them?",
"What have you learned from your mistakes?",
"What did you like or dislike about your previous job?",
"Which was most / least rewarding?",
"What was the biggest accomplishment / failure in this position?",
"Questions about job demotions.",
"Questions about your supervisors and co-workers.",
"What was it like working for your supervisor?",
"What do you expect from a supervisor?",
"What problems have you encountered at work?",
"Have you ever had difficulty working with a manager?",
"Have you worked with someone who didn't like your work?",
"How did you fit in with the company culture?",
"Who was your best boss and who was the worst?",
"Describe your ideal boss.",
"Describe the gap in your employment history.",
"Why are you leaving your job?",
"Why do you want to change jobs?",
"Why were you fired?",
"Why were you laid-off?",
"Why did you quit your job?",
"Why did you resign?",
"What have you been doing since your last job?",
"Why have you been out of work so long?",
"Why weren't you promoted at your last job?",
"What were your starting and final levels of compensation?",
"What are your salary expectations?",
"What are your salary requirements - both short-term and long-term?",
"Why would you take a job for less money?",
"Should employees use social media at work?",
"What interests you about this job?",
"Why do you want this job?",
"What can you do for this company?",
"Why should we hire you?",
"Why shouldn't we hire you?",
"Why should we hire you instead of the other applicants for the job?",
"Why are you the best person for the job?",
"What do you know about this company?",
"Why do you want to work here?",
"What challenges are you looking for in a position?",
"What can we expect from you in the first 60 days on the job?",
"What can you contribute to this company?",
"What do you see yourself doing within the first 30 days on the job?",
"What would you do if you found out the company was doing something illegal?",
"Are you willing to travel?",
"What are the most significant trends in your field?",
"What is good customer service?",
"How long do you expect to remain employed with this company?",
"When could you start work?",
"Please rate me as an interviewer.",
"Is there anything I haven't told you about the job or company that you would like to know?",
"What are you looking for in your next job? What is important to you?",
"Where do you see yourself 5 years from now?",
"Where do you see yourself in 10 years? (for older applicants)",
"What are your goals for the next five years / ten years?",
"How do you plan to achieve those goals?",
"How would you feel about working for a younger manager?",
"More questions about your career goals.",
"What will you do if you don't get this position?",
"Where else are you interviewing?"]
